USE [doan]
GO

/****** Object:  Table [dbo].[ChienDich]    Script Date: 12/30/2023 3:01:53 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[ChienDich](
	[IDKM] [bigint] NOT NULL,
	[IDSP] [bigint] NOT NULL,
 CONSTRAINT [PK_ChienDich] PRIMARY KEY CLUSTERED 
(
	[IDKM] ASC,
	[IDSP] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


